[project]
name = "to-svg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "streamlit>=1.46.0",
    "svgwrite>=1.4.3",
]
